version: "3"

services:
  tinyurl:
    build: ./tinyurl
    volumes:
      - ./tinyurl:/app
    networks:
      - tinyurl_network
    depends_on: 
      - redis

  redis:
    image: 'redis:3.2-alpine'
    expose:
      - "6379"
    networks:
      - tinyurl_network
    volumes:
      - "redis-data:/data"
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks: 
      - tinyurl_network
    depends_on: 
      - tinyurl

volumes:
  redis-data:

networks:
  tinyurl_network:
